// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfMvvmDiEfSample.Data;

#nullable disable

namespace WpfMvvmDiEfSample.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20220713114503_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("WpfMvvmDiEfSample.Models.Band", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Metal",
                            Name = "As I Lay Dying"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Alternative",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "NewWave",
                            Name = "Hobostank"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
